### ISSUE TITLE
Checkin z2w

### ISSUE THREAD

**Issue by croyerbai** [BoulderAmp/z2w-6.6.44-rt49#1]
Grant Coby access. (I can't assign this issue to Adam.)
Check in kernel code.
Make public (right?)

**Comment by adamtorgerson** [comment]
I pushed https://github.com/BoulderAmp/linux-rpi-6.6.y/tree/6.6.54%2B-rt43 ... 6.6.44 was already out of date. There is also a 6.11.y, but it looks like that is not yet ready for primetime.

**Comment by croyerbai** [comment]
Ok thanks for updateOn Oct 8, 2024, at 12:43 PM, Adam Torgerson ***@***.***> wrote:﻿
I pushed https://github.com/BoulderAmp/linux-rpi-6.6.y/tree/6.6.54%2B-rt43 ... 6.6.44 was already out of date. There is also a 6.11.y, but it looks like that is not yet ready for primetime.
